### ISSUE TITLE
Make Ice Web Wallpaper Static and not reactive

### ISSUE THREAD

**Issue by ghost** [vikas5914/wallpaper-engine-issues#1]
Dude Its A dope wallpaper. but I wish there was a way I could turn off the mouse interaction, because it annoys me. so could you please make it so I can turn that off........ Thanks

**Comment by vikas5914** [comment]
Done.

**Comment by vikas5914** [comment]
@SharpShadowFTW can you confirm if its working ?

**Comment by ghost** [comment]
Omg, thanks so much.... IT works!!!

Op zo 9 sep. 2018 om 18:19 schreef Vikas Kapadiya <notifications@github.com>

**Comment by ghost** [comment]
Hello Vikas,
ive used ice web now for a day and i notice that if i restart my laptop,
the repulse activates again. This is weird because the repulse disabled
button is still crossed.
what ive done is just turn repulse off and on again and then it works
again.
could this be a program on my side or could it be a problem with the
wallpaper?
if it is the problem of the wallpaper could u fix this? like some way
refresh it when it startups or something.

Thanks
_SharpShadow_

Op zo 9 sep. 2018 om 20:19 schreef Robin Mager <robinmager21@gmail.com>:

**Comment by vikas5914** [comment]
@SharpShadowFTW Fixed..
