### ISSUE TITLE
Ice web 

### ISSUE THREAD

**Issue by ghost** [vikas5914/wallpaper-engine-issues#2]
Now every time I startup the ice web repulse is glitched out and it responds, even tho repulse disabled is crossed. I usually fix it with turning “disable repulse” off and on again.
Could you please fix this

**Comment by vikas5914** [comment]
Its problem of both wallpaper and the application. 

Use this attached zip. I have disabled the click in JavaScript. 

In Wallpaper engine, click on Open from a file -> select the index.html. 

I will re-write this wallpaper later or next month. 

[Ice Web No Click.zip](https://github.com/vikas5914/Ice-web/files/2367352/Ice.Web.No.Click.zip)

**Comment by vikas5914** [comment]
@SharpShadowFTW  did you tried the attached wallpaper ?

**Comment by ghost** [comment]
Yes I did and it worked exactly as I wanted to
Thanks
SharpShadow

Op do 13 sep. 2018 om 13:44 schreef Vikas Kapadiya <notifications@github.com
